#-----------------------------Global configs -----------------------------------#
server:
 port: 8083

#Local AWS Dynamodb Config
local:
 amazon:
  dynamodb:
   mode: local
   endpoint: http://localhost:8000/
   credentials:
    access-key: key
    secret-key: key2
   signingregion: ap-south-1
   record-expiration: 15552000

#AWS Dynamodb Config
amazon:
 dynamodb:
  mode: remote
  signingregion: us-west-2
  record-expiration: 15552000